package util

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	foundryv1 "github.com/GiorgosAlexakis/fab/internal/foundry/v1"
)

func TestLoadLockMissing(t *testing.T) {
	_, err := LoadLock(t.TempDir())
	if !errors.Is(err, ErrNoLock) {
		t.Fatalf("LoadLock() error = %v, want ErrNoLock", err)
	}
}

func TestSaveLockWritesAHeader(t *testing.T) {
	root := t.TempDir()
	lock := &foundryv1.Lock{
		APIVersion: foundryv1.APIVersion,
		Kind:       foundryv1.LockKind,
	}
	if err := SaveLock(root, lock); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(root, LockFileName))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "# Generated by `fab resolve`") {
		t.Errorf("lock file does not start with the generated header:\n%s", data)
	}
}
