package util

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"sigs.k8s.io/yaml"

	foundryv1 "github.com/GiorgosAlexakis/fab/internal/foundry/v1"
)

var ErrNoLock = errors.New("no foundry.lock")

func LoadLock(root string) (*foundryv1.Lock, error) {
	path := filepath.Join(root, LockFileName)

	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("%s: %w", path, ErrNoLock)
		}
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	lock := &foundryv1.Lock{}
	if err := yaml.Unmarshal(data, lock); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return lock, nil
}

func SaveLock(root string, lock *foundryv1.Lock) error {
	data, err := yaml.Marshal(lock)
	if err != nil {
		return fmt.Errorf("encoding %s: %w", LockFileName, err)
	}

	header := "# Generated by `fab resolve`. Commit this file; do not edit it.\n"
	path := filepath.Join(root, LockFileName)
	if err := os.WriteFile(path, append([]byte(header), data...), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
