/*
Copyright The FAB Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package layers

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLockRoundTrips(t *testing.T) {
	root := writeLayers(t,
		layerSpec{name: "meta-elo", version: "1.0.3"},
		layerSpec{name: "meta-core", version: "1.0.1", dependsOn: []string{"meta-elo"}},
	)

	resolution, err := resolve(t, root, configFor("meta-elo", "meta-core"))
	if err != nil {
		t.Fatalf("Resolve() failed: %v", err)
	}

	lock, err := NewLock(resolution)
	if err != nil {
		t.Fatalf("NewLock() failed: %v", err)
	}
	if err := SaveLock(root, lock); err != nil {
		t.Fatalf("SaveLock() failed: %v", err)
	}

	reloaded, err := LoadLock(root)
	if err != nil {
		t.Fatalf("LoadLock() failed: %v", err)
	}
	if len(reloaded.Locked) != 2 {
		t.Fatalf("got %d locked layers, want 2", len(reloaded.Locked))
	}
	if reloaded.Locked[0].Name != "meta-elo" || reloaded.Locked[1].Name != "meta-core" {
		t.Errorf("lock does not preserve build order: %v", lockNames(reloaded))
	}
	if !strings.HasPrefix(reloaded.Locked[0].Digest, "sha256:") {
		t.Errorf("digest = %q", reloaded.Locked[0].Digest)
	}

	changes, err := reloaded.Diff(resolution)
	if err != nil {
		t.Fatalf("Diff() failed: %v", err)
	}
	if len(changes) != 0 {
		t.Errorf("a freshly written lock should be current, got %v", changes)
	}
}

func TestLoadLockMissing(t *testing.T) {
	_, err := LoadLock(t.TempDir())
	if !errors.Is(err, ErrNoLock) {
		t.Fatalf("LoadLock() error = %v, want ErrNoLock", err)
	}
}

// The lock is a comment header plus YAML, so a reviewer reading the diff knows
// not to edit it.
func TestSaveLockWritesAHeader(t *testing.T) {
	root := writeLayers(t, layerSpec{name: "meta-elo", version: "1.0.0"})
	resolution, err := resolve(t, root, configFor("meta-elo"))
	if err != nil {
		t.Fatal(err)
	}
	lock, err := NewLock(resolution)
	if err != nil {
		t.Fatal(err)
	}
	if err := SaveLock(root, lock); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(root, LockFileName))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "# Generated by `fab resolve`") {
		t.Errorf("lock file does not start with the generated header:\n%s", data)
	}
}

func TestDiffReportsAddedRemovedAndChangedLayers(t *testing.T) {
	root := writeLayers(t,
		layerSpec{name: "meta-elo", version: "1.0.0"},
		layerSpec{name: "meta-core", version: "1.0.0", dependsOn: []string{"meta-elo"}},
	)
	resolution, err := resolve(t, root, configFor("meta-elo", "meta-core"))
	if err != nil {
		t.Fatal(err)
	}

	stale := &Lock{Locked: []LockedLayer{
		{Name: "meta-elo", Version: "0.9.0"},
		{Name: "meta-gone", Version: "1.0.0"},
	}}

	changes, err := stale.Diff(resolution)
	if err != nil {
		t.Fatalf("Diff() failed: %v", err)
	}

	joined := strings.Join(changes, "\n")
	for _, want := range []string{"~ meta-elo 0.9.0 -> 1.0.0", "+ meta-core 1.0.0", "- meta-gone 1.0.0"} {
		if !strings.Contains(joined, want) {
			t.Errorf("Diff() = %v, want a line %q", changes, want)
		}
	}
}

// A layer edited in place without a version bump is exactly the drift a digest
// is there to catch.
func TestDiffNoticesAnEditWithoutAVersionBump(t *testing.T) {
	root := writeLayers(t, layerSpec{name: "meta-elo", version: "1.0.0"})
	resolution, err := resolve(t, root, configFor("meta-elo"))
	if err != nil {
		t.Fatal(err)
	}
	lock, err := NewLock(resolution)
	if err != nil {
		t.Fatal(err)
	}

	lock.Locked[0].Digest = "sha256:0000"

	changes, err := lock.Diff(resolution)
	if err != nil {
		t.Fatal(err)
	}
	if len(changes) != 1 || !strings.Contains(changes[0], "without a version bump") {
		t.Errorf("Diff() = %v, want a digest change", changes)
	}
}

// The merge order decides which layer can reference which types, so a reordering
// is a change even when the layer set is identical.
func TestDiffNoticesAReorder(t *testing.T) {
	root := writeLayers(t,
		layerSpec{name: "meta-elo", version: "1.0.0"},
		layerSpec{name: "meta-core", version: "1.0.0", dependsOn: []string{"meta-elo"}},
	)
	resolution, err := resolve(t, root, configFor("meta-elo", "meta-core"))
	if err != nil {
		t.Fatal(err)
	}
	lock, err := NewLock(resolution)
	if err != nil {
		t.Fatal(err)
	}

	lock.Locked[0], lock.Locked[1] = lock.Locked[1], lock.Locked[0]

	changes, err := lock.Diff(resolution)
	if err != nil {
		t.Fatal(err)
	}
	if len(changes) == 0 || !strings.Contains(strings.Join(changes, "\n"), "build order") {
		t.Errorf("Diff() = %v, want a build order change", changes)
	}
}
