-- Copyright The FAB Authors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- The ontology registry: the metadata plane.
--
-- Identity is deliberately split across two levels:
--
--   * The catalog tables (ont_type_catalog, ont_prop_catalog, ont_link_catalog)
--     allocate a small integer id per (layer, type) or (type, property) pair.
--     These ids are append-only, never reused, and independent of any ontology
--     version. They are what the object store stores in every row.
--
--   * The per-version tables (ont_object_types, ont_properties, ont_link_types)
--     describe what a given ontology version says about those ids.
--
-- The split is what lets a schema change be a metadata-only operation: renaming
-- Customer.email to Customer.contact_email publishes a new version that maps
-- the same prop_id to a new name, and not one object row is rewritten.

-- Named, versioned ontology snapshots. A snapshot is complete and immutable:
-- there are no diffs and no parent references.
CREATE TABLE ontologies (
    ontology_id  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text        NOT NULL,
    version      text        NOT NULL,
    status       text        NOT NULL
        CHECK (status IN ('draft', 'published', 'deprecated')),
    -- Content digest of the compiled snapshot, as computed by the compiler.
    -- Re-publishing the same version with different content is rejected by
    -- comparing this value.
    digest       text        NOT NULL,
    -- Commit the snapshot was compiled from, when published from a git tree.
    git_ref      text,
    -- Contributing layers, in merge order.
    layers       text[]      NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz,
    UNIQUE (name, version)
);

CREATE INDEX ontologies_by_name ON ontologies (name, created_at DESC);

-- Environment tags. One ontology version per tag, swapped atomically by
-- `fab schema promote`.
CREATE TABLE ontology_tags (
    name        text        NOT NULL,
    tag         text        NOT NULL,
    ontology_id bigint      NOT NULL REFERENCES ontologies (ontology_id),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (name, tag)
);

-- Append-only history of every tag movement. This is what makes
-- `fab schema rollback` possible without guessing: the previous value of a tag
-- is a fact, not an inference from version ordering.
CREATE TABLE ontology_tag_events (
    event_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    tag         text        NOT NULL,
    ontology_id bigint      NOT NULL REFERENCES ontologies (ontology_id),
    occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ontology_tag_events_by_tag ON ontology_tag_events (name, tag, event_id DESC);

-- Version-independent identity for object types.
CREATE TABLE ont_type_catalog (
    type_id    int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layer      text        NOT NULL,
    name       text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (layer, name)
);

-- Version-independent identity for properties. A property is identified by the
-- object type that owns it plus its name, so two types may both have an "email"
-- property and still get distinct prop_ids.
CREATE TABLE ont_prop_catalog (
    prop_id    int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id    int         NOT NULL REFERENCES ont_type_catalog (type_id),
    name       text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (type_id, name)
);

-- Version-independent identity for link types.
CREATE TABLE ont_link_catalog (
    link_id    int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layer      text        NOT NULL,
    name       text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (layer, name)
);

-- What one ontology version says about an object type.
CREATE TABLE ont_object_types (
    ontology_id         bigint NOT NULL REFERENCES ontologies (ontology_id) ON DELETE CASCADE,
    type_id             int    NOT NULL REFERENCES ont_type_catalog (type_id),
    layer               text   NOT NULL,
    name                text   NOT NULL,
    description         text   NOT NULL DEFAULT '',
    primary_key_prop_id int    NOT NULL REFERENCES ont_prop_catalog (prop_id),
    PRIMARY KEY (ontology_id, type_id),
    UNIQUE (ontology_id, layer, name)
);

-- What one ontology version says about a property.
CREATE TABLE ont_properties (
    ontology_id bigint  NOT NULL,
    prop_id     int     NOT NULL REFERENCES ont_prop_catalog (prop_id),
    type_id     int     NOT NULL,
    name        text    NOT NULL,
    data_type   text    NOT NULL,
    -- Element type for array properties.
    items_type  text,
    -- Permitted values for enum properties, in declared order.
    enum_values text[],
    nullable    boolean NOT NULL,
    is_unique   boolean NOT NULL,
    indexed     boolean NOT NULL,
    description text    NOT NULL DEFAULT '',
    PRIMARY KEY (ontology_id, prop_id),
    FOREIGN KEY (ontology_id, type_id)
        REFERENCES ont_object_types (ontology_id, type_id) ON DELETE CASCADE,
    UNIQUE (ontology_id, type_id, name)
);

-- What one ontology version says about a link type. Endpoints are catalog type
-- ids: the compiler has already proved both ends resolve.
CREATE TABLE ont_link_types (
    ontology_id      bigint NOT NULL REFERENCES ontologies (ontology_id) ON DELETE CASCADE,
    link_id          int    NOT NULL REFERENCES ont_link_catalog (link_id),
    layer            text   NOT NULL,
    name             text   NOT NULL,
    description      text   NOT NULL DEFAULT '',
    source_type_id   int    NOT NULL REFERENCES ont_type_catalog (type_id),
    target_type_id   int    NOT NULL REFERENCES ont_type_catalog (type_id),
    cardinality      text   NOT NULL,
    forward_name     text   NOT NULL,
    reverse_name     text   NOT NULL,
    on_source_delete text   NOT NULL,
    PRIMARY KEY (ontology_id, link_id),
    UNIQUE (ontology_id, layer, name)
);

CREATE INDEX ont_link_types_by_source ON ont_link_types (ontology_id, source_type_id);
CREATE INDEX ont_link_types_by_target ON ont_link_types (ontology_id, target_type_id);
