-- Copyright The FAB Authors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- The object store: the data plane.
--
-- Objects are separated from their properties. An object row is identity and
-- lifecycle; a property row is one current value. There is no table per object
-- type and no column per property, so publishing a new ontology version is a
-- metadata operation in the registry and never a migration here.
--
-- Every id in this schema that names something in the ontology -- object_type_id,
-- prop_id, link_id -- is a catalog id from the registry. There is no foreign key
-- to the registry: the two planes may live in different databases, and the plans
-- allow a deployment to separate them. The store validates ids against the
-- ontology it is bound to before writing, which is where that integrity is
-- enforced.

-- One row per object instance.
CREATE TABLE objects (
    object_id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Catalog type id from the registry (ont_type_catalog.type_id).
    object_type_id int         NOT NULL,
    -- The value of the object type's primary key property, rendered as text.
    -- It is duplicated as a property row; this column is what makes identity
    -- lookups a single index probe and what enforces uniqueness per type.
    primary_key    text        NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (object_type_id, primary_key)
);

CREATE INDEX objects_by_type ON objects (object_type_id, object_id);

-- Current property values, one row per (object, property).
--
-- This table holds no history. An object's previous values are not here at all:
-- edit history is an append-only store of its own, so that the hot read path
-- stays one index probe per object and never filters by validity window.
CREATE TABLE object_props (
    object_id  bigint      NOT NULL REFERENCES objects (object_id) ON DELETE CASCADE,
    -- Catalog property id from the registry (ont_prop_catalog.prop_id).
    prop_id    int         NOT NULL,
    value      jsonb,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (object_id, prop_id)
);

-- Supports "find the objects whose property X equals Y". jsonb has a total btree
-- ordering, so one index serves equality and range predicates for every scalar
-- property type.
CREATE INDEX object_props_by_value ON object_props (prop_id, value);

-- Uniqueness declared in the ontology, enforced by the database.
--
-- A unique property cannot have its own unique index without a DDL statement per
-- property, which is exactly what this schema exists to avoid. Instead a write
-- to a unique property also writes here, and the primary key does the enforcing.
-- Values are normalized to text so that 1 and 1.0 cannot both be inserted.
CREATE TABLE object_prop_unique (
    prop_id    int    NOT NULL,
    value_text text   NOT NULL,
    object_id  bigint NOT NULL REFERENCES objects (object_id) ON DELETE CASCADE,
    PRIMARY KEY (prop_id, value_text)
);

CREATE INDEX object_prop_unique_by_object ON object_prop_unique (object_id, prop_id);

-- Link instances. A link is a first-class edge, not a foreign key: it is stored
-- once and traversable from either end.
CREATE TABLE object_links (
    -- Catalog link id from the registry (ont_link_catalog.link_id).
    link_id          int         NOT NULL,
    source_object_id bigint      NOT NULL REFERENCES objects (object_id) ON DELETE CASCADE,
    target_object_id bigint      NOT NULL REFERENCES objects (object_id) ON DELETE CASCADE,
    created_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (link_id, source_object_id, target_object_id)
);

-- The primary key serves forward traversal; this index serves the reverse
-- direction, which is what makes a link queryable both ways.
CREATE INDEX object_links_by_target ON object_links (link_id, target_object_id, source_object_id);
